---
- debug:
    msg:
      - "Plan: {{ _apb_plan_id }}"
      - "HA: {{ ha }}"
      - "Update: {{ update }}"
      - "Test: {{ test }}"

- include_tasks: "{{ plan_states[_apb_plan_id][ha] }}.yml"

# Run tests after deployment is complete
- include_tasks: "test.yml"
  when: test

