---

- include_tasks: "update_step_a.yml"
  when: update

- include_tasks: "service.yml"

- debug:
    msg:
      - "Create PV"
      - "Create DeploymentConfig"

- include_tasks: "update_step_b.yml"
  when: update
